from_banned_800 = ['blogfalconstudios.com', 'mynakedteens.com', 'older-beauty.com', 'bestmilfsporn.com',
                   'xnxx-free.net',
                   'beurettehot.net', 'heganporn.com', 'videos.petardas.com', 'boytikol.com',
                   'gracefulnudes.com',
                   'herbalviagraworld.com', 'grandmammapics.com', 'milfkiss.com', 'indienne-sexy.com',
                   'peliculaspornogratisxxx.com', 'eros.com', 'lustfuloldies.com', 'maturelle.com',
                   'nonvegjokes.com',
                   'sexymaturepics.com', 'milfera.com', 'liberteenage.com', 'salope-marocaine.com',
                   'tube8.com',
                   'pornmotion.com', 'pornovideo.italy.com', 'maturehere.com', '30yomilf.com',
                   'numaturewomen.com',
                   'bitefaim.com', 'bettermilfs.com', 'largepontube.com', 'teen18ass.com',
                   'm.chudaimaza.com',
                   'chocomilf.com', 'xnxx.vc', '8nsex.com', 'hotnudematures.com', 'porno-wife.com',
                   'pornokutusu.com',
                   'sex.pornoxxl.org', 'goodgrannypics.com', 'sexcoachapp.com', 'xxxvideo.com',
                   'fsiblog.com',
                   'pinkvisualtgp.com', 'maturedolls.net', 'hairy.com', 'cliphunter.com', 'home-madness.com',
                   'mommyxxxmovies.com', 'oldernastybitches.com', 'alizjokes.blogspot.in', 'motherless.com',
                   'nudematurepussy.com', 'beeg.co', 'tiny-cams.com', 'indiangilma.com',
                   'thematureladies.com',
                   'xebonygirls.com', 'hotelmatures.com', 'lewdmistress.com', 'idealwifes.com',
                   'momsecstasy.com',
                   'mouparkstreet.blogspot.com', 'milfionaire.com', 'tubefellas.com', 'xesi.mobi',
                   'momhandjob.com',
                   'couleurivoire.com', 'every-seconds.tumblr.com', 'matureladiespics.com',
                   'chubbygalls.com',
                   'adultfriendfinder.com', 'onlyporngif.com', 'xxxbunker.com', 'riomature.com',
                   'poringa.net',
                   'find-best-videos.com', 'es.bravotube.net', 'beautiful-nude-teens-exposed.tumblr.com',
                   'gaygautemela.com',
                   'dustyporn.com', 'silkymoms.com', 'xxl.sexgratuits.com', 'oldercherry.com', 'porn720.com',
                   'matureladies.com', 'fuckmycheatingslutwife.tumblr.com', 'desikamasutra.com',
                   'daultpornvideox.com',
                   'myfreecams.com', 'indianhotjokes.blogspot.in', 'vintagehairy.net', 'broslingerie.com',
                   'redtube.com',
                   'matureintros.com', 'maturosexy.com', 'awesomeellalove.tumblr.com', 'chubbygirlpics.com',
                   'ilovematurewomen.tumblr.com', 'hairymilfpics.com', 'sexocean.com', 'fatsexygirls.net',
                   'pahubad.com',
                   'lushstories.com', 'womanolder.com', 'maturebrotherthumbs.com', 'xxx.adulttube.com',
                   'premium.gays.com',
                   'lookatvintage.com', 'maturenags.com', 'hyat.mobi', 'nautilix.com', 'milfjam.com',
                   'hqoldies.com',
                   'adultwork.com', 'horny-matures.net', 'wetmaturewomen.com', 'store.falconstudios.com',
                   'maturecherry.net',
                   'pornodoido.com', 'old-vulva.com', 'videosfilleschaudes.com', 'pinkythekinky.com',
                   'erotic-olders.com',
                   'askyourmommy.com', 'momshere.com', 'muyzorras.com', 'hot-dates.info',
                   'bigbuttmature.com',
                   'tgpmaturewoman.com', 'maturemomsex.com', 'ww.lastsexe.com', 'kickass.com',
                   'juicy-matures.com',
                   'dslady.com', 'wetmaturewhores.com', 'fantasticwomans.com', 'momsforporn.com',
                   'indiansgoanal.org',
                   'pornmaturepics.com', 'mature30plus.com', 'pornorc.net', 'pornosfilms.com', 'sex.com',
                   '40somethingmag.com', 'mature-library.com', 'sexyhotmilfs.com', 'llveleak.com',
                   'pornoriver.net',
                   'woodstockreborn.tumblr.com', 'kilopics.com', 'perfectgirls.net', 'bravioteens.com',
                   'mturemomsporn.com',
                   'callboyindia.com', 'video.freex.mobl', 'maghrebinnes.xl.cx', 'fapto.xxx',
                   'en.cam4.com.br',
                   'tour.fuckmyindiangf.com', 'fakku.net', 'maturesensations.com', 'milfgals.net',
                   'momsclan.com',
                   'eroticbeauties.net', 'pamelapost.com', 'watchersweb.com', 'nudedares.tumblr.com',
                   'allofteens.com',
                   'bigtitsnaked.com', 'bigtinz.com', 'wifesbank.com', 'immodestmoms.com', 'arabesexy.com',
                   'theporndude.com', 'maturepornhere.com', 'tubexclips.com', 'babosas.com', 'rk.com',
                   'lewd-girls.com',
                   'funjadu.com', 'moncotube.net', 'mature-for-you.com', 'myhotsite.net', 'porn.com',
                   'theofficiallouisejenson.com', 'mature.nl', 'xxxmaturepost.com', 'oldhotmoms.com',
                   'picsboob.com',
                   'dildosatisfaction.tumblr.com', 'epicporntube.com', 'sexonapria.org', 'matureclits.net',
                   'alohatube.com',
                   'lisaannlovers11.tumblr.com', 'sexynakedamateurgirls.com', 'tukif.com', 'popurls.com',
                   'maturedummy.com',
                   'sexymaturepussies.com', 'youngxxxpics.com', 'milf-fucking.net', 'teengayporntube.com',
                   'yehfun.com',
                   'videosanalesx.com', 'pornhub.com', 'xnxx.com', 'pornnakedgirls.com', 'petiteporn.pw',
                   'maturecool.com',
                   '30plusgirls.com', 'momsinporn.net', 'freshmatureporn.com', 'darering.com',
                   'film-xxx-black.com',
                   'x-ho.com', 'xnxxgifs.com', 'fuckmaturewhore.com', 'sexy-links.net', 'nudeartstars.com',
                   'boyddl.com',
                   'owerotica.com', 'pornxxxtubes.com', 'indiankahani.com', 'shemales.com',
                   'maturewitch.com',
                   'thegranny.net', 'olderwomenarchive.com', 'joncjg.blogspot.in',
                   'girthyencounters.tumblr.com',
                   'mypornbookmarks.com', 'legalporno.com', 'posingwomen.com', 'pornfromczech.com',
                   'saoulbafjojo.com',
                   'videos-x.xpornogays.com', 'gentlemoms.com', 'smutty.com', 'fr-nostradamus.com',
                   'eternaldesire.com',
                   'secinsurance.com', 'thexmilf.com', 'grandmabesttube.com', 'cochonnevideosx.com',
                   'xmilfpics.com',
                   'bravomamas.com', 'sexymilfpussy.com', 'freshporn.info', 'xhot.sextgem.com', '3movs.com',
                   'grannyxxx.co.uk', 'free-porn-pics.net', 'thehotpics.com', 'babes.com',
                   'pornocolumbia.co',
                   'porno-algerienne.com', 'videos-porno.x18xxx.com', 'unshavengirls.net', 'agedcunts.net',
                   'pinkcupid.com',
                   'jav-porn.net', 'desimurga.com', 'desisexclips.com', 'x-art.com', 'wegret.com',
                   '7dog.com',
                   'teencamvids.org', 'dailyolders.com', 'maturepicsarchive.com', 'mulligansmilfs.com',
                   'stretchedpussy.tumblr.com', 'queenofmature.com', 'locasporfollar.com', 'xxxsummer.net',
                   'youporn.com',
                   'porn20.org', 'sexybuttpics.com', 'imomsex.com', 'teensnowxvideos.com',
                   'nakedoldbabes.com',
                   'bestmatureclips.com', 'omegaporno.com', 'xxx.com', 'flirthookup.com', 'maturegirl.us',
                   'ixxx.com.es',
                   'bigfreemature.com', 'momspics.net', 'el-ladies.com', 'naked-moms.com', 'milfsbeach.com',
                   'fucking8.com',
                   'xpornking.com', 'desindian.sextgem.com', 'shemale.asia', 'amapics.net',
                   'pretty-matures.com',
                   'maturepornpics.com', 'olderkiss.com', 'in.spankbang.com', 'salope.1japonsex.com',
                   'matureandyoung.com',
                   'hotamateurclip.com', 'pornstarhangout.com', 'riotits.net', 'videos-sexe.1touffe.com',
                   'xxxvideosex.org',
                   'viewmature.com', 'elderly-women.com', 'hairymaturegirls.com', 'squirtingmastery.com',
                   'videosdemadurasx.com', 'indiansexstories.net', 'freex.mobi', 'myonlyhd.com',
                   'tinysolo.com',
                   'indianpornvideos.com', 'xxxolders.com', 'sexy-olders.com', 'h33t.to',
                   'freemilfpornpics.com',
                   'pornoforo.com', 'womeninyears.com', 'freeporndr.com', 'haporntube.com', 'breeolson.com',
                   'momsnightjob.com', 'adultphonechatlines.co.uk', 'bizzzporno.com', 'gratishentai.net',
                   'efukt.com',
                   'posing-matures.com', 'tubegogo.com', 'toroporno.com', 'nuvid.com', 'fr.perfectgirls.net',
                   'matureplace.com', 'beautyandthebeard1.tumblr.com', 'gggay.com', 'kingsizebreasts.com',
                   'gayboystube.com',
                   'fillechaude.com', 'gobeurettes.com', 'hotnakedoldies.com', 'needmilf.com',
                   'maturesexy.us', 'gay43.com',
                   'teenpornxxx.net', 'sexbotbonnasse.com', 'mature-women-tube.net', 'wild-matures.com',
                   'mature4.net',
                   'bigtitsporn.me', 'arabe-sexy.com', 'nudemomphotos.com', 'maturebabesporno.com',
                   'oldwomanface.com',
                   '10pointz.com', 'watchmygf.com', 'azgals.com', 'teenpussy.pw', 'maturemompics.com',
                   'brazzersnetwork.com',
                   'bigboty4free.com', 'amateur-sexys.tumblr.com', 'alansanal.com', 'classic-moms.com',
                   'matureinlove.net',
                   'mature30-45.com', 'sexpics.xxx', 'actuallyattractiveamateurs.tumblr.com', 'conejox.com',
                   'stripping-moms.com', 'fuckdc.com', 'maturehotsex.com', 'video-sex.femmesx.net',
                   'myhdshop.com',
                   'videos-porno-chaudes.com', 'eatyouout.tumblr.com', 'boutique-sexy.ch',
                   'xxi.onxxille.com',
                   'youngmint.com', 'collegehumor.com', 'tubegalore.com', 'matureguide.com',
                   'es.bongacams.com',
                   'maturestation.com', 'eroticplace.net', 'sexualolders.com', 'filthymamas.com',
                   'fresh-galleries.com',
                   'disco-girls.com', 'jizzporntube.com', 'kissmaturesgo.com', 'primecurves.com',
                   'numoms.com',
                   'teemns-pic.com', 'pornmirror.com', 'imagefap.com', 'megavideoporno.org',
                   'freekiloclips.com',
                   'babesclub.net', 'masalopeblack.com', 'nexxx.com', 'matureandgranny.com',
                   'amateurmaturewives.com',
                   'pornochaud.com', 'porno.com', 'babosas.co', 'savitabhabhi.mobi', 'rude.com',
                   'jizzle.com',
                   'xxxkinky.com', 'mrskin.com', 'pinkworld.com', 'lenawethole.com', 'maturepornqueens.net',
                   'mom50.com',
                   'sexe-evbony.com', 'oldsweet.com', 'sexyteensphotos.com', 'unshavenpussies.net',
                   'hornybook.com',
                   'tubepornstars.com', 'cholotube.com', 'golden-moms.com', 'horny-olders.com',
                   'es.porn.com',
                   'ass-butt.com', 'cumlouder.com', 'themomsfucking.net', 'milfsection.met',
                   '18teensexposed.tumblr.com',
                   'yourather.com', 'cloaktube.com', 'jeunette18.com', 'vivthomas.com', 'nudevista.com',
                   'hard.pornoxxl.org',
                   'oldpoon.com', 'premiercastingporno.com', 'megamovie.us', 'befuck.com', 'ixxx.com',
                   'xhamster.com',
                   'bushypussies.net', 'sexsex.hu', '3animalsextube.com', 'xvideosnacional.com',
                   'coffetube.com',
                   'jeux-flash-sexy.com', 'milfparanoia.com', 'truthordarepics.com', 'en.cam4.co', 'fuq.com',
                   'parejasfollando.es', 'nudematurewomenphotos.com', 'upskirttop.net', 'jlobster.com',
                   'culx.org',
                   'ovideox.com', 'cullosgratis.com.ve', 'mygranny.pics', 'gaypornium.com', 'webcam.com',
                   'rubber-kingdom.com', 'hindiold.com', 'porntubevidz.com', 'riomoms.com', 'ass4all.com',
                   'boobymilf.com',
                   'bangbros.com', 'hotmomsporn.com', 'onlygirlvideos.com', 'video-porno.1lecheuse.com',
                   'allindiansexstories.com', 'ohasiatique.com', 'nudeboobshotpics.com', 'maturewant.com',
                   'eroticteens.pw',
                   'pornhubfillesalope.com', 'leche69.com', 'aztecaporno.com', 'nudematuremix.com',
                   'specialgays.com',
                   'jpangel101.tumblr.com', 'cleomture.com', 'yasminramos.com', 'wethairywats.com',
                   'hotchicks.sexy',
                   'hotmomspics.com', 'shitbrix.com', 'agedmamas.com', 'maturetube.com',
                   'iloveindiansex.com',
                   'xxxmomclips.com', 'xxx.xxx', 'bigtitsfree.net', 'japanesexxxtube.com', '105matures.com',
                   'vipoldies.net',
                   'jeffdunhamfuckdoll.com', 'tendance-lesbienne.com', 'mindslostinlust.tumblr.com',
                   'iknowthatgirl.com',
                   'pandamovies.com', 'mature-beach.com', 'foto-erotica.es', 'bomnporn.com', 'mc-nudes.com',
                   'porn00.org',
                   'femmesporno.com', 'des-filles-sexy.com', 'sexyhotmilf.com', 'matureland.net',
                   'milfbank.com',
                   'khu18.biz', 'kickass.co', 'lechecallente.com', 'pornmdk.com', 'hqmaturemovs.com',
                   'milfpornet.com',
                   'milfsaffair.com', 'oldmomstgp.com', 'beauxcul.com', 'ladymom.com', 'perucaseras.com',
                   'playboy.com',
                   'bigtitsmilf.com', 'tubeduporno.com', 'arabicdancevideo.blogspot.com',
                   'find-best-lingerie.com',
                   'naughty.com', 'allindiansex.com', 'wetmaturepics.com', 'nakedboobs.net',
                   'desikahani.net',
                   'sambaporno.com', 'lovely-mature.net', '4hen.com', 'inlovewithboobs.com', 'xtube.com',
                   'lesbiennesxxx.com', 'sexymaturethumbs.com', 'milfpicshere.com', 'uniquesexymoms.com',
                   'spankwire.com',
                   'femmesmuresx.net', 'lewd-babes.com', 'pornmaturewomen.com', 'sexyono.com', 'godao.com',
                   'gokabyle.com',
                   'mega-teen.com', 'thefreecamsecret.com', 'womenmaturepics.com', 'bestmaturewomen.com',
                   'gramateurs.com',
                   'stiflersmoms.com', 'toonztube.com', 'xbabe.com', 'mature-galleries.org',
                   'hot-naked-milfs.com',
                   'alloldpics.com', 'cleoteener.com', 'antarvasna.com', 'drtuber.com',
                   'sweetmaturepics.com',
                   'hollywoodjizz.com', 'freeones.ch', 'bollywood-sex.net', 'marocainenue.com',
                   'whoresmilfsdegraded.tumblr.com', 'desipapa.com', 'barstoolsports.com', 'chaturbate.com',
                   'cocomilfs.com',
                   'xtube.nom.co', 'sexxxxi.com', 'excitingmatures.com', 'voyeurpipi.com', 'cinedunia.com',
                   '6mature9.com',
                   'wifenaked.net', 'cuckinohio.tumblr.com', 'madmamas.com', 'milfmomspics.com',
                   'porno-marocaine.com',
                   'bullporn.com', 'maturepornhub.com', 'porndig.com', 'fille-nue-video.com',
                   'gracefulmom.com',
                   'eroticperfection.com', 'africansexvideos.net', 'puritanas.com', 'hotsexyteensphotos.com',
                   'teensnow.com',
                   'pornsticky.com', 'pornerbros.com', 'milfatwork.net', 'tubestack.com',
                   'pornstarnirvna.com',
                   'bbwpornpics.com', 'milfs30.com', 'hungrymatures.com', 'wifezilla.com',
                   'immoralmatures.com',
                   'playvid.com', 'tnaflix.com', 'icematures.com', 'femdomecpire.com',
                   'bigdickswillingchicks.tumblr.com',
                   'kink.com', 'beeg.com', 'cam4.in', 'es.chaturbate.com', 'nudeold.com', 'gracefulmilf.com',
                   'hardsextube.com', 'roundandbrown.com', 'hindisex.com', 'ah-me.com',
                   'hardsexyyoupornhub.com',
                   'owsmut.com', 'galsarchive.com', 'pornofemmeblack.com', 'iscindia.org', 'alexmatures.com',
                   'matureclithunter.com', 'katestube.com', 'axnxxx.org', 'freematurepornpics.com',
                   'masturbationaddicton.net', 'hqlinks.net', 'amazingmaturesluts.com',
                   'bestmaturesthumb.com', '7feel.net',
                   'hot-gifz.com', 'bdenjoymore.blogspot.com', 'nakedbustytits.com', 'matureshine.com',
                   'superdiosas.com',
                   'momsteachsex.com', 'maturexxxclipz.com', 'mature-women-tube.org', 'place21.com',
                   'milfsarea.com',
                   'bananabunny.com', 'matureholes.net', 'hindi-sex.net', 'upskirt.com', 'riomilf.com',
                   'ixxx-tube.com',
                   'pinkteenpics.com', 'motherstits.com', 'maturesort.com', 'cheatwife.com', 'pornzz.com',
                   'cindymovies.com',
                   'nude-oldies.com', 'gaytube.com', 'gonzo.com', 'belles-femmes-arabes.blogspot.com',
                   'gonzoxxxmovies.com',
                   'stiflersmilfs.com', 'eeltube.com', 'desitales.com', 'action36.com', 'grannyhairy.net',
                   'freemilfsite.com', 'hothomemadepix.tumblr.com', 'sharedxpics.com', 'youjizz.ws',
                   'porny.com',
                   'brazzers.com', 'dagay.com', 'goulnes.pornoxxxi.net', 'freesex.com',
                   'maturenakedsluts.com',
                   'adultreviews.com', 'ixxx.ws', 'how-do-you-produce-more-seminal-fluid.semenaxx.org',
                   'dreammovies.com',
                   'milfous.com', 'dixvi.com', 'pornorama.com', 'girlygifporn.com', 'asiatique-femme.com',
                   'xvideos.com',
                   'yourlustgirlfriends.com', 'xixx.com', 'sex3.com', 'petardas.com', 'porntube.com',
                   'oigh.info',
                   'multimature.com', 'booloo.com', 'cutepornvideos.com', 'kellydivine.co',
                   'fresholders.com',
                   'labatidora.net', 'ahmilf.com', 'webpnudes.com', 'kirtu.com', 'bubblebuttpics.com',
                   'immaturewomen.com',
                   'ashleyrnadison.com', 'zmilfs.com', 'livjasmin.com', 'rubias19.com',
                   'fotomujeres.pibones.com',
                   'arabebaise.com', 'girlmature.com', 'randyhags.com', 'jizzhut.com', 'indlansex.net',
                   '89.com',
                   'xgouines.com', 'insext.net', 'clit7.com', 'mature-orgasm.com', 'anatarvasnavideos.com',
                   'videospornonacional.com', 'matureasspics.com', 'teenpornjoy.com', 'adultsextube.com',
                   'dianapost.com',
                   'videosxxxputas.xxx', 'video-one.com', 'pinksofa.com', 'pornxxx.com', 'maturedally.net',
                   'hdrolet.com',
                   'top-chatroulette.com', 'bestmilftube.com', 'pinsex.com', 'milffreepictures.com',
                   'esseporn.com',
                   'film-porno-black.com', 'hotfreemilfs.com', 'penguinvids.com', 'xxxonxxx.com',
                   'flirt4free.com',
                   'everydaycams.com', 'ebonyfantasies.com', 'luboeporno.com', 'bigboobsalert.com',
                   'porn.mangassex.com',
                   'fuckcuck.com', 'gorgeousladies.com', 'mamitatube.com', 'empflix.com',
                   'live.sugarbbw.com',
                   'amaclips.com', 'wixvi.com', 'sextubelinks.com', 'indiansex4u.com', 'worldxxxphotos.com',
                   'bootlus.com',
                   'myfreemoms.com', 'eporner.com', 'imaturewomen.com', 'idealmilf.com',
                   'myfreepornvideos.net',
                   'newsfilter.org', 'teenhana.com', 'sexe2asiatique.com', 'pof.com', '3rat.com',
                   'private.com',
                   'slutload.com', 'momstaboo.com', 'digitalplayground.com', 'ledauphine.com',
                   'dorceltv.xn.pl',
                   'matures-photos.com', 'nudematurespics.com', '9gag.tv', 'analsexstars.com',
                   'realitypassplus.com',
                   'juliepost.com', 'amateur-libertins.net', 'indianporntube.xxx', 'cerdas.com',
                   'sexxxdoll.com',
                   'freeones.com', 'purebbwtube.com', 'youngpornvideos.com', 'roflpot.com',
                   'es.xhamster.com',
                   'video-porno.videurdecouilles.com', 'matureal.com', 'maturesinstockings.com',
                   'voyeursport.com',
                   'uplust.com', 'grannypornpics.net', 'pornotantique.com', '2gayboys.com',
                   'pussy-mature.com',
                   'jrunk.tumblr.com', 'chaudassedusexe.com', 'nudemomandboy.com', '69rueporno.com',
                   'myexmilf.com',
                   'redtuve.com', 'eromatures.net', 'milfmovs.com',
                   'all-free-nude-old-granny-mature-women-xxx-porn-pics.com', 'les-groses.net',
                   'milftubevids.com',
                   'deviantclip.com', 'youjizz.com', 'juicygranny.com', 'comicmasala.com',
                   'secretarypics.com',
                   'universeold.com', 'filthyoldies.com', 'yourlust.com', 'olderwomentaboo.com',
                   'keezmovies.com',
                   'buzzwok.com', 'freematurevideo.net', 'matureamour.com', 'fuck-milf.com',
                   'oldsexybabes.net',
                   'indianpornovid.com', 'matureoracle.com', 'guide-asie.com', 'serviporno.com']

free_porn_tubes = ['3movs.com', 'pornhits.com', 'daftsex.com', 'letsjerk.cc', 'reddit.tube', 'tube8.com',
                   'youporn.com', 'pornktu.be', 'godude.link', 'xozilla.com', 'tubxporn.xxx', 'pandamovies.pw',
                   'hqporner.com', 'porndish.com', 'youjizz.com', 'whoreshub.com', 'pornhd3x.tv', 'j-pussy.com',
                   'pornhd.com', 'txxx.com', 'porndoe.com', 'yespornpleasexxx.com', 'pornovideoshub.com',
                   'pornhat.com', 'freeomovie.to', 'hotgirlclub.com', 'paradisehill.cc', 'motherless.com',
                   'xnxx.com', 'pornky.com', 'dvdtrailertube.com', 'casting-porno-tube.com', 'xfreehd.com',
                   'xxxfiles.com', 'pornvibe.org', 'veporno.net', 'pornwiss.com', 'hd-easyporn.com', '4kporn.xxx',
                   'likuoo.video', 'severeporn.com', 'megatube.xxx', 'xtapes.to', 'perfectgirls.net',
                   'pornobae.com', 'anysex.com', 'drtuber.com', 'fapster.xxx', 'porngo.com', 'porn00.org',
                   'porndune.com', 'porntrex.com', 'collectionofbestporn.com', 'anyporn.com', 'tnaflix.com',
                   'streamporn.pw', 'pornone.com', 'sexu.com', 'xxxscenes.net', 'taxi69.com', 'vxxx.com',
                   'fapmeifyoucan.net', 'cliphunter.com', 'trendyporn.com', 'empflix.com', 'euroxxx.net',
                   'beeg.com', 'porndig.com', 'pornhd8k.net', 'czechvideo.org', 'sextvx.com', 'xxxfree.watch',
                   'palmtube.com', 'eporner.com', 'xdporner.com', 'mangoporn.net', 'tube.perverzija.com',
                   'justfullporn.com', 'fullporner.com', 'ok.xxx', 'xmoviesforyou.com', 'plusone8.com',
                   'xmegadrive.com', 'gotporn.com', 'yourdailypornvideos.ws', 'hdporn92.com', 'pussyspace.com',
                   'latestporn.co', 'porn4days.biz', 'siska.video', 'pornmz.com', 'xhamster.com', 'porn300.com',
                   '4tube.com', 'joysporn.com', 'watchporninpublic.com', 'veporn.com', 'slutload.com',
                   'thepornfull.com', 'porntop.com', 'swingerpornfun.com', 'netfapx.com', 'pornwild.to',
                   'justswallows.com', 'pornhub.com', 'spankbang.com', 'iceporncasting.com', 'xkeezmovies.com',
                   'fux.com', 'gameofporn.net', 'sxyprn.com', 'goodporn.to', 'redtube.com', 'hitprn.com',
                   'fullxxxmovies.net', 'povcum.com', 'analdin.com', 'porntube.com']

only_fans_leak = ['thotbook.tv', 'bitchesgirls.com', 'nsfwbomb.com', 'famousinternetgirls.pw', 'thotpacks.com',
                  'premiumbooty.com', 'onlyfansleaks.com', 'findhername.net', 'onlyfaps.club',
                  'voyeurflash.com', 'thottok.com', 'siteripz.net', 'tuqpa.com', 'fikfap.com', 'fansteek.com',
                  'theleakbay.com', 'fapopedia.net', 'yesleaks.com', 'thotseek.com', 'leakedbb.com', 'segavideo.xyz',
                  'lewdthots.com', 'nudecosplaygirls.com', 'porntn.com', 'prothots.com', 'jizzy.org', 'sexy-egirls.com',
                  'dirtyship.com', 'nsfw247.to', 'influencersgonewild.com', 'fapfappy.com', 'fansleaks.com',
                  'xxxtik.com', 'celebjared.net', 'viraltags.xyz', 'lewdhub.net', 'thotleaks.org', 'sorrymother.video',
                  'ibradome.com', 'thotslife.com', 'cyberleaks.to', 'nudostar.com', 'evilx.su', 'eroleaks.com',
                  'lewdstars.com', 'realpornclip.com', 'nudes7.com', 'hotscope.tv', 'internetchicks.com',
                  'onlythots.org', 'leakedmodels.com', 'thothub.to', 'teenager365.com',
                  'famousinternetgirlsgalleries.com', 'pureleaks.net']

asian_porn_tubes = ['javgiga.com', 'iyotvideos.com', 'freejav.guru', 'kantotero.net', 'ww1.chinababe.net',
                    'tokyomotion.com', 'pornbraze.com', 'javrank.com', 'tokyomotion.net', 'pornhub.com', 'camcam.cc',
                    'javseen.tv', 'javmost.com', 'javfindx.com', '91porn.com', 'javleak.com', 'popjav.tv', 'bejav.net',
                    'javfun.me', 'javdisk.com', 'herexxx.com', 'vjav.com', 'javbangers.com', 'javbraze.com',
                    'avgle.com', 'sarapbabe.com', 'avcrempie.com', 'javrave.club', 'javqd.me', 'javtiful.com',
                    'jav19.com', 'sexkbj.com', 'supjav.com', 'missav.com', 'javjack.com', 'thisav.com', 'jav.guru',
                    'sextop.net', 'simpasian.net', 'xtorjack.com', 'kissjav.com', 'javhd.today', 'javtsunami.com',
                    'hpjav.tv', 'javshujin.com', 'bestjavporn.com', 'liboggirls.net', 'watchjavonline.com', 'fbjav.com',
                    'ww1.javbabe.net', 'sextb.net', 'iyottube.com', 'javfinder.la', 'pinaypornsite.com']

hentai_porn_tubes = ['kemono.party', 'e-hentai.org', 'chan.sankakucomplex.com', 'rule34.paheal.net', 'shadbase.com',
                     'rule34.xyz', 'fapforfun.net', 'hentai-foundry.com', 'luscious.net', 'naughtymachinima.com',
                     'rule34.xxx', 'studiofow.com', 'whentai.com', 'hentaifromhell.org', 'pixiv.net', 'yande.re',
                     'danbooru.donmai.us', 'sankakucomplex.com', 'xbooru.com', 'gelbooru.com', 'giantessbooru.com',
                     'e621.net', 'derpibooru.org', 'hypnohub.net', 'thehentaiworld.com', 'fapservice.com',
                     'exhentai.org', 'inkbunny.net', 'furaffinity.net', 'lolhentai.net', 'rule34.us', 'baraag.net',
                     'footfetishbooru.booru.org', 'rule34hentai.net']

hentai_streaming_sites = ['hentaihaven.com', 'hentai.animestigma.com', 'hentai-moon.com', 'hentaiworld.tv',
                          'xanimeporn.com', 'ohentai.org', 'hentaimama.io', 'underhentai.net', 'pornhub.com',
                          'tube.hentaistream.com', 'hentais.tube', 'hentaigasm.com', 'miohentai.com', 'rule34video.com',
                          'hentaitube.online', 'hentaiplay.net', 'hentaifox.tv', 'hentai.tv', 'hanime.tv',
                          'animeidhentai.com', 'hentaicore.org', 'hentaiyes.com', 'muchohentai.com', 'hentaicloud.com',
                          'hentaifreak.org', 'erotic-hentai.com', 'xvideos.com']

tabboo_porn_sites = ['familyporn.tv', 'tabootube.xxx', 'tabooporns.com', 'incestflix.com', 'xhamster.com',
                     'incestvidz.com', 'motherless.com', 'onlycestporn.com', 'milfnut.com', 'justfamilyporn.com',
                     'tabooporn.tv', 'incestporn.xxx', 'familypornhd.com', 'milfzr.com']

hentai_manga_sites = ['pururin.to', 'hbrowse.com', 'hitomi.la', 'hentaifox.com', '9hentai.to', 'tsumino.com',
                      'fakku.net', 'manytoon.com', 'hentairox.com', 'manhwahentai.me', 'hentaiera.com', 'imhentai.xxx',
                      'nhentai.com', 'nhentai.xxx', 'hentaihere.com', 'hentairead.com', 'm-hentai.net',
                      'hentaihand.com', 'asmhentai.com', 'multporn.net', 'hentai2read.com', 'mangahentai.me',
                      'simply-hentai.com', 'nhentai.net', 'doujins.com']

porn_comic_sites = ['hentaicomicsfree.com', 'multporn.net', 'lewdua.com', 'bondagecomixxx.net', 'xlecx.org',
                    'mycomicsxxx.com', 'freeadultcomix.com', 'xcomics.se', 'oglaf.com', 'comicporn.xxx', 'lacomics.net',
                    'svscomics.com', 'incognitymous.com', 'palcomix.com', 'mult34.com', 'xxxcomics.online',
                    'porncomixonline.net', 'porncomixinfo.net', 'porncomixone.net', 'myhentaicomics.com',
                    'nxt-comics.net', 'allporncomic.com', '8muses.one', 'kingcomix.com', 'ilikecomix.com',
                    'masttram.com', 'bestporncomix.com', 'shentai.org', 'xyzcomics.com', 'erofus.com', 'savitahd.net',
                    'myhentaigallery.com', 'comixzilla.com', 'porncomixonline.com']

free_sex_games = ['summertimesaga.com', 'h-flash.com', 'fap-nation.com', 'playforceone.com', 'runey42.itch.io',
                  'steamunlocked.net', 'gamcore.com', 'f95zone.to', 'free-strip-games.com', 'mysexgames.com',
                  'cloudmeadowgame.com', 'loverslab.com', 'wetpussygames.com', 'androidadult.com', 'porngames.games',
                  'fenoxo.com', 'redamz.itch.io', 'otomi-games.com', 'playporngames.com', 'patreon.com', 'nlt.itch.io',
                  'yanderesimulator.com', 'violatedheroine.referata.com', 'porngames.com', 'bestporngames.com',
                  'new.lewd.ninja', 'taifunriders.blogspot.com', 'trapquest.com', 'adult-sex-games.com',
                  'hdoomguy.newgrounds.com', 'gamepcfull.com', 'comdotgame.com', 'gamesofdesire.com', 'xgames.zone',
                  'teamsadcrab.com', 'lewdzone.com', 'sirensdomain.itch.io', 'spnati.net', 'katawa-shoujo.com',
                  'playsexgames.xxx', 'itch.io', 'igg-games.com', 'teamamorous.itch.io', 'yiffalicious.com',
                  'mythicmanor.com', 'newgrounds.com', 'majalis.itch.io', 'adultgamesworld.com',
                  'lilithsthrone.blogspot.com', 'godude.link']

porn_gifs_sites = ['iloopit.net', 'nsfwmonster.com', 'pornhub.com', 'gifporntube.com', 'redgifs.com', 'hardgif.com'
    , 'gifsauce.com', 'imagefap.com', 'sex.com', 'gifhq.com']

full_porn_movie_sites = ['pornvibe.org', 'xdporner.com', 'xxxfiles.com', 'justfullporn.com', 'hdporn92.com',
                         'likuoo.video', 'eporner.com', 'plusone8.com', 'pornhd3x.tv', 'hqporner.com', 'pornmz.com',
                         'pornobae.com', 'daftsex.com', 'netfapx.com', 'pornovideoshub.com', 'swingerpornfun.com',
                         'casting-porno-tube.com', 'xtapes.to', 'xmoviesforyou.com', 'hitprn.com', 'trendyporn.com',
                         'xxxfree.watch', 'paradisehill.cc', 'watchporninpublic.com', 'pornwiss.com', 'veporno.net',
                         'freeomovie.to', 'pornhd8k.net', 'latestporn.co', 'sxyprn.com', 'joysporn.com', 'letsjerk.cc',
                         'yespornpleasexxx.com', 'thepornfull.com', 'pornktu.be', 'czechvideo.org', 'xfreehd.com',
                         'tubxporn.xxx', 'siska.video', 'porndune.com', 'streamporn.pw', 'fullporner.com',
                         'tube.perverzija.com', 'porndish.com', 'goodporn.to', 'fullxxxmovies.net', 'porn4days.biz',
                         'xmegadrive.com', 'pornky.com', 'iceporncasting.com', 'theporndude.com', 'mangoporn.net',
                         'porn00.org', 'pornhits.com', 'porntrex.com', 'xxxscenes.net', 'gameofporn.net',
                         'pandamovies.pw', 'porngo.com']

amateur_porn_sites = ['camwhoresbay.com', 'nsfw247.to', 'thecuckold.com', 'motherless.com', 'uflash.tv', 'godude.link',
                      'cambro.tv', 'ruleporn.com', 'eroprofile.com', 'pornhub.com', 'mylust.com', 'truthordarepics.com'
    , 'youramateurporn.com', 'watchersweb.com', 'myxclip.com', 'hobby.porn',
                      'xvideos.com', 'camvideos.tv', 'homemoviestube.com', 'submityourflicks.com', 'dirtyship.com',
                      'hclips.com', 'camwhores.tv', 'erome.com', 'hotscope.tv', 'xhamster.com',
                      'famousinternetgirls.pw', 'realgfporn.com', 'watchmygf.me', 'xxbrits.com', 'adultism.com',
                      'thecandidbay.com']

free_cam_girl_video_sites = ['sexkbj.com', 'camwhoresbay.com', 'oncam.me', 'camvideos.tv', 'godude.link',
                             'watchfreejavonline.co', 'camwhores.tv', 'webcamrips.com', 'camshowdownload.com',
                             'camcaps.to', 'tubeasiancams.com', 'cambro.tv', 'rechub.tv', 'koreanbj.club']

porn_picture_sites = ['amabitch.com', 'hqbabes.com', 'instantfap.com', 'sexycandidgirls.com', 'reddpics.com',
                      'chatpic.org', 'sex.com', 'nsfw.xxx', 'tubeteencam.com', 'pmatehunter.com', 'asiaon.top',
                      'sxypix.com', 'pics.vc', 'sexygirlspics.com', 'babesource.com', 'pornhub.com', 'fap.bar',
                      'mitaku.net', 'nude-gals.com', 'jjgirls.com', 'imagefap.com', 'pornpics.com', 'pichunter.com',
                      'adultmagazine.net', 'pornpaw.com', 'erotelki.org', 'pictoa.com', 'fuskator.com',
                      'motherless.com', 'bunnyfap.com', 'stufferdb.com', 'pornedup.com', 'candidteens.top',
                      'nude-modelz.com', 'xhamster.com', 'smutty.com']

the_fappening = ['fappenist.com', 'celebsroulette.com', 'thefappeningblog.com', 'thefappening.pro', 'motherless.com',
                 'aznude.com', 'celebrityslips.com', 'socialmediagirls.com', 'thenipslip.com', 'egotastic.com',
                 'ancensored.com', 'thefappening.wiki', 'taxidrivermovie.com', 'celeb.gate.cc', 'drunkenstepfather.com',
                 'nudography.com', 'scandalplanet.com', 'wikifeet.com', 'fappeningbook.com',
                 'heroero.com', 'jerkofftocelebs.com']

deep_fake_sites = ['sexcelebrity.net', 'mrdeepfakes.com', 'adultdeepfakes.com', 'porndeepfake.net', 'imagefap.com',
                   'deepfakeporn.net', 'desifakes.com', 'cfake.com', 'celebjihad.com', 'famousboard.com',
                   'sexystars.online']

pov_porn_sites = ['daftsex.com', 'xvideos.com', 'hqporner.com', 'ixxx.com', 'pornpics.com', 'sex.com', 'sxyprn.net',
                  'povcum.com', 'porntrex.com', 'alohatube.com', 'pornhub.com', 'scrolller.com',
                  'naughtyblog.org', 'rarbgmirror.com', 'nudevista.com', 'iwank.tv', 'imagefap.com', 'xhamster.com',
                  'eporner.com']

indian_porn_tube_sites = ['exmovies.co.in', 'xhamster.com', 'antarvasnaclips.com', 'kamababa.com', 'masalaseen.net',
                          'videbd.net', 'pornhub.com', 'indianpornvideos.vip', 'pornxnow.me', 'lustesthd.com',
                          'xxxvideoindian.com', 'fry99.com', 'xvideos.com', 'xnxx.com', 'sucksex.com', 'dropmms.com',
                          'freesexyindians.com', 'auntymaza.com']

arab_porn_sites = ['sexsaoy.com', 'xnxxarab.cc', 'sexjk.com', 'aflamporn.com', 'xhamster.com', 'motherless.com',
                   'sex4arab.xxx', 'xnxx.com', 'arabysexy.com', 'aflamsexnek.com', 'sexalarab.com', 'xvideos.com',
                   'pornhub.com']

latina_porn_sites = ['xvideos.com', 'xpaja.net', 'novinhasdozapzap.com', 'brasiltudoliberado.com', 'naoconto.com',
                     'colegialasdeverdad.com', 'espaporn.com', 'cnnamador.com', 'xhamster.com', 'pornhub.com',
                     'pornocarioca.com', 'pornolandia.xxx', 'xnalgas.com']

black_porn_sites = ['naijauncut.com', 'darknaija.com', 'mzansixxx.com', 'shegotass.info', 'baddiesonly.tv',
                    'xvideos.com', 'iponsex.com', 'hoodamateurs.com', 'bangher.net', 'mzansipornvideos.com',
                    'shesfreaky.com', 'pornhub.com', 'homegrownfreaks.net', 'ebonygalore.com', 'djatoya.com',
                    'baddiehub.com', 'xhamster.com', 'seneporno.com', 'ebonypulse.tv', 'ghettotube.com',
                    'tastyblacks.com']

extreme_porn_sites = ['darknessporn.com', 'bestrapeporn.com', 'crazyshit.com', 'en.luxuretv.com', 'cutscenes.net',
                      'twistedporn.com', 'goreforum.com', 'xrares.com', 'kaotic.com', 'rapefilms.net', 'theync.com',
                      'deepgoretube.site', 'sickjunk.com', 'rapelust.com']

free_porn_download_sites = ['hqcollect.net', 'femdomcc.net', 'top-modelz.org', 'xxxstreams.org', 'siteripz.com',
                            'adultmagz.com', 'femdomup.net', 'adultmagazine.net', 'hotpornfile.org', 'newestxxx.com',
                            'naughtyblog.org', 'asiaon.top', 'filesmonster.vip', 'pornorips.com', '0xxx.ws',
                            'incezt.net', 'fisting.vip', 'transporn.vip', 'hidefporn.ws', 'hard-extreme.com',
                            'siterips.org', 'scatfile.com', 'voyeurpapa.com', 'niceupskirt.com', 'bestpornstars.org',
                            'copro.pw', 'shemale777.com', 'sexgalaxy.net', 'adultbay.org', 'javlibrary.com',
                            '3xplanet.com', 'piratecams.vip', 'adultmagazinespdf.com', 'mitaku.net', 'piratecams.com',
                            'pornmagnet.org', 'hornywhores.net', 'evilfist.com', 'girlscanner.cc', 'new-jav.net',
                            'seaporn.org', 'streamingporn.xyz']

porn_forums = ['hot-board.net', 'peefans.com', 'fritchy.com', 'cyberleaks.to', 'peachyforum.com', 'pornbb.org',
               'cumonprintedpics.com', 'board.freeones.com', 'forum.xnxx.com', 'extreme-board.com', 'planetsuzy.org',
               'forum.oneclickchicks.com', 'vipergirls.to', 'leakedbb.com', 'dropmms.com', 'forum.adultdvdtalk.com',
               'forums.socialmediagirls.com', 'f95zone.to', 'onlyfansforum.famousinternetgirls.com', 'yesleaks.com',
               'rawporn.org', '85.17.187.83', 'theoriginalcandid.com', 'forum.phun.org', 'forums.sexyandfunny.com',
               'vintage-erotica-forum.com', 'kitty-kats.net', 'amateurvoyeurforum.com', 'sextingforum.net',
               'eroticity.net', 'dickflash.com', 'forumophilia.com', 'camcaps.net', 'nudecelebforum.com',
               'forum.sexy-egirls.com', 'porn-w.org', 'pornsavant.com']

lesbian_porn_sites = ['pornpics.com', 'xvideos.com', 'naughtyblog.org', 'noodlemagazine.com', 'literotica.com',
                      'alohatube.com', 'xhamster.com', 'daftsex.com', 'eporner.com', 'sxyprn.com', 'pornhub.com',
                      'sex.com', 'iwank.tv', 'vipergirls.to', 'ixxx.com', 'xnxx.com', 'rarbgmirror.com',
                      'porngo.com', 'nudevista.com', 'lesbianpornvideos.com', 'porntrex.com', 'imagefap.com',
                      'redtube.com', 'scrolller.com', 'hqporner.com']

porn_for_womens = ['iwank.tv', 'nudevista.com', 'forhertube.com', 'xvideos.com', 'daftsex.com', 'alohatube.com',
                   'eporner.com', 'xhamster.com', 'hqporner.com', 'sex.com', 'pornpics.com', 'pornhub.com',
                   'scrolller.com', 'bellesa.co', 'tumblr.com', 'sxyprn.com']

sex_stories_sites = ['fimfiction.net', 'asstr.org', 'adult-fanfiction.org', 'hyperdreams.com',
                     'sexstories.com', 'opentgc.com', 'mcstories.com', 'chyoa.com', 'bdsmcafe.com', 'storiesonline.net',
                     'fictionmania.tv', 'sexualstories.club', 'literotica.com', 'noveltrove.com',
                     'indiansexstories2.net', 'bdsmlibrary.com', 'lushstories.com', 'sexstories69.com', 'nifty.org']

asmr_porn_sites = ['eroasmr.com', 'hentaiasmr.moe', 'japaneseasmr.com', 'spankbang.com', 'lushstories.com',
                   'tryquinn.com', 'xhamster.com', 'ixxx.com', 'orgasmsoundlibrary.com',
                   'literotica.com', 'flaru.com', 'pornhub.com', 'dl.erovoice.us', 'xvideos.com', 'asmrland.website',
                   'nudevista.com']

pornstar_database_and_directories = ['boobpedia.com', 'pornteengirl.com', 'adultdvdtalk.com', 'definefetish.com',
                                     'adultfilmdatabase.com', 'babepedia.com', 'freeones.com', 'dbnaked.com',
                                     'iafd.com', 'babesandstars.com', 'shemalestardb.com', 'definebabe.com',
                                     'javlibrary.com', 'europornstar.com', 'mypornstarbook.net']

bdsm_pron_tubes = ['feet9.com', 'thisvid.com', 'femdomup.net', 'heavy-r.com', 'fitnakedgirls.com', 'freeuseporn.com',
                   'pornbimbo.com', 'femefun.com', 'punishbang.com', 'hitbdsm.com', 'pornhub.com', 'hypnoporn.net',
                   'bdsmstreak.com', 'footstockings.com', 'motherless.com', 'boundhub.com', 'pornfd.com',
                   'cosplayporntube.com', 'hcbdsm.com', 'hypnotube.com', 'stocking-tease.com', 'tubebdsm.com',
                   'spankingtube.com']

anal_porn_tubes = ['hqporner.com', 'porntrex.com', 'pornhub.com', 'xvideos.com', 'xhamster.com', 'sxyprn.com',
                   'eporner.com', 'daftsex.com', 'assoass.com', 'ass4all.com']

teen_porn_sites = ['xhamster.com', 'xvideos.com', 'youngpornvideos.com', 'forumophilia.com',
                   'porntrex.com', 'teensnow.com', 'hqporner.com', 'sxyprn.com', 'pornktu.be', 'daftsex.com',
                   'pornhub.com']

mature_porn_sites = ['milffox.com', 'xhamster.com', 'milfmovs.com', 'el-ladies.com', 'hqporner.com', 'daftsex.com',
                     'xvideos.com', 'porntrex.com', 'sxyprn.com', 'milf300.com', 'pornhub.com', 'maturetube.com']

blowjob_porn_sites = ['iwank.tv', 'nudevista.com', 'porntrex.com', 'pornpics.com', 'xhamster.com', 'imagefap.com',
                      'alohatube.com', 'sex.com', 'pornhub.com', 'eporner.com', 'scrolller.com', 'mrdeepfakes.com',
                      'porngo.com', 'sxyprn.com', 'hqporner.com', 'daftsex.com', 'deepthroatx.com',
                      'cumswallowclips.com', 'rarbgmirror.com', 'justswallows.com', 'noodlemagazine.com', 'xvideos.com'
    , 'naughtyblog.org', 'cumswallowingmovies.org', 'gloryholecumswallow.com', 'ixxx.com']

creampie_porn_sites = ['imagefap.com', 'pornhub.com', 'hqporner.com', 'ixxx.com', 'iwank.tv',
                       'daftsex.com', 'eporner.com', 'scrolller.com', 'porngo.com', 'xnxx.com', 'motherless.com',
                       'pornpics.com', 'xhamster.com', 'nudevista.com', 'naughtyblog.org', 'alohatube.com',
                       'porntrex.com', 'xvideos.com', 'sex.com', 'sxyprn.com', 'rarbgmirror.com']

vintage_porn_sites = ['xhamster.com', 'cat3movie.org', 'ixxx.com', 'vidsgator.com', 'vintagepornfun.com',
                      'tubepornclassic.com', 'pornhub.com', 'motherless.com', 'xvideos.com', 'alohatube.com',
                      'vintagetube.xxx', 'adultmagz.com', 'imagefap.com']

funny_porn_sites = ['imagefap.com', 'sex.com', 'humoron.com', '9gag.com', 'efukt.com', 'inhumanity.com',
                    'daftporn.com']

voyeur_porn_sites = ['voyeur-house.club', 'imagefap.com', 'thecandidforum.com', 'uflash.tv', 'motherless.com',
                     'reallifecam.to', 'camcaps.net', 'thecandidbay.com', 'ixxx.com', 'xhamster.com',
                     'sexycandidgirls.com', 'voyeurhit.com', 'voyeurweb.com', 'amateurvoyeurforum.com',
                     'voyeur-house.life', 'alohatube.com', 'pornpics.com', 'theoriginalcandid.com', 'pornhub.com',
                     'xvideos.com', 'candidteens.top', 'niceupskirt.com']

big_tit_porn_sites = ['xtits.com', 'xnxx.com', 'spicybigtits.com', 'gigantits.com', 'porngo.com', 'melonstube.com',
                      'sex.com', 'primecurves.com', 'bigboobsfilm.com', 'xvideos.com', 'imagefap.com', 'hqporner.com',
                      'scrolller.com', 'titshits.com', 'daftsex.com', 'pornhub.com', 'nudevista.com',
                      'xhamster.com', 'eporner.com', 'boobpedia.com', 'curvyerotic.com', 'alohatube.com',
                      'porntrex.com', 'ixxx.com', 'pornpics.com']

porn_aggregators = ['lobstertube.com', 'dinotube.com', 'maturetube.com', '4porn.com', 'tubegalore.com',
                    'tonicmovies.com', 'tubegals.com', 'iwank.tv', 'pornsos.com', 'pinkdino.com', 'ixxx.com',
                    'porzo.com', 'fapvid.com', 'alohatube.com', 'thumbzilla.com', 'tubepornstars.com', 'tubesafari.com',
                    'melonstube.com', 'tiava.com', 'pornogo.tv', 'pornkai.com', 'fuq.com', 'booloo.com',
                    'video-one.life']

porn_search_engines = ['namethatpornstar.com', 'ro89.com', 'namethatporn.com', 'nudevista.com', 'pornstarbyface.com',
                       'boodigo.com', 'findtubes.com', 'porndex.com', 'pornmd.com', 'xfantazy.com',
                       'noodlemagazine.com']

escort_sites = ['tsescorts.com', 'escortbabylon.net', 'eroticmonkey.ch', 'ts4rent.eu', 'eros.com', 'perb.cc',
                'leolist.cc', 'newzealandgirls.co.nz', 'escortdex.com', 'cityxguide.app', 'ii.skokka.com',
                'sumosear.ch', 'angelsoflondon.com', 'sexadvisor.com', 'eurogirlsescort.com', 'usasexguide.nl',
                'uescort.com', 'escort-ireland.com', 'topescortbabes.com', 'massagerepublic.com', 'escortdirectory.com',
                'terb.cc', 'harlothub.com', 'skipthegames.com', 'adultsearch.com', 'escortrankings.uk', 'ukpunting.com',
                'megapersonals.eu', 'merb.cc', 'tnaboard.com', 'diorescorts.com', 'in.locan.to', 'bedpage.com',
                'slixa.com', 'eccie.net', 'escortguide.co.uk', 'lovehub.com', 'escortsaffair.com', 'humpchies.com',
                'godude.link', 'adultseek.com', 'listcrawler.com', 'escortnews.eu', 'scarletblue.com.au']

other_domains = ['de.pornhub.com', 'fr.pornhub.com', 'es.pornhub.com', 'it.pornhub.com', 'pt.pornhub.com',
                 'pl.pornhub.com', 'rt.pornhub.com', 'jp.pornhub.com', 'nl.pornhub.com', 'cz.pornhub.com',
                 'cn.pornhub.com', 'xhamster.desi', 'xhamster1.desi', 'blacked.com', 'onlyfans.com', 'modelhub.com',
                 'smutcam.com', 'manyvids.com', 'pronhub.com', 'xhamster18.desi', 'xlivesex.com', 'onlyindianporn2.com',
                 'masterdesi.com', 'xnxxgood.com', 'sexyoung.me', 'hdmovie20.com', 'hotasiansex.mobi', 'upornia.com',
                 'porngo.tube']

all = list(set(escort_sites + porn_search_engines + porn_aggregators + big_tit_porn_sites + voyeur_porn_sites
       + funny_porn_sites + vintage_porn_sites + creampie_porn_sites + blowjob_porn_sites + mature_porn_sites
       + teen_porn_sites + anal_porn_tubes + bdsm_pron_tubes + pornstar_database_and_directories + asmr_porn_sites
       + sex_stories_sites + porn_for_womens + porn_forums + lesbian_porn_sites + free_porn_download_sites
       + extreme_porn_sites + black_porn_sites + latina_porn_sites + arab_porn_sites + indian_porn_tube_sites
       + pov_porn_sites + deep_fake_sites + the_fappening + porn_picture_sites + free_cam_girl_video_sites
       + amateur_porn_sites + full_porn_movie_sites + porn_gifs_sites + free_sex_games + porn_comic_sites
       + hentai_manga_sites + tabboo_porn_sites + hentai_streaming_sites + hentai_porn_tubes + asian_porn_tubes
       + only_fans_leak + free_porn_tubes + from_banned_800 + other_domains))

if __name__ == '__main__':
    print(all)
    print(len(all))
